<a href="https://colab.research.google.com/github/Nadacc/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
array=np.random.randint(10,size=(3,3))
print(array)

[[0 0 0]
 [0 0 2]
 [3 0 3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [3]:
#please provide your answer below this line.
import numpy as np
array1=np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[2 9 8 7]
 [9 3 8 6]
 [6 8 0 5]
 [7 9 3 6]]
[[3 4 9 3]
 [3 2 0 0]
 [9 0 5 9]
 [4 0 0 3]]
[[2 9 8 7 9 3 8 6]
 [6 8 0 5 7 9 3 6]
 [3 4 9 3 3 2 0 0]
 [9 0 5 9 4 0 0 3]]
[[2 9 8 7 9 3 8 6 3 4 9 3 3 2 0 0]
 [6 8 0 5 7 9 3 6 9 0 5 9 4 0 0 3]]
